CREATE TABLE IF NOT EXISTS CUSTOMERS (
  ID       INT(11)      NOT NULL AUTO_INCREMENT,
  EMAIL    VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  NAME     VARCHAR(100) NOT NULL,
  TYPE     TINYINT(4)   NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT CUSTOMERS_EMAIL_UINDEX UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
  ID                  INT(11)      NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID         INT(11)      NOT NULL,
  COMPANY_NAME        VARCHAR(100) NULL,
  COMPANY_WEBSITE     VARCHAR(100) NULL,
  COMPANY_DESC        VARCHAR(100) NULL,
  COMPANY_LOGO        VARCHAR(100) NULL,
  COMPANY_GOOGLE_PLUS VARCHAR(100) NULL,
  COMPANY_FACEBOOK    VARCHAR(100) NULL,
  COMPANY_LINKEDIN    VARCHAR(100) NULL,
  COMPANY_TWITTER     VARCHAR(100) NULL,
  COMPANY_INSTAGRAM   VARCHAR(100) NULL,
  MEMBER_TYPE         TINYINT(4)   NOT NULL,
  DUE_DATE            DATETIME     NULL,
  PRIMARY KEY (ID),
  CONSTRAINT EMPLOYEES_CUSTOMER_ID_UINDEX UNIQUE (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS JOBS (
  ID          INT(11)      NOT NULL AUTO_INCREMENT,
  EMPLOYEE_ID INT(11)      NOT NULL,
  TITLE       VARCHAR(100) NOT NULL,
  DESCRIPTION LONGTEXT     NULL,
  LOCATION    VARCHAR(255) NOT NULL,
  TYPE        TINYINT(4)   NOT NULL,
  CLOSING     DATETIME     NULL,
  EMAIL       VARCHAR(255) NOT NULL,
  REG_DATE    DATETIME     NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS APPLICATION (
  ID           INT(11)  NOT NULL AUTO_INCREMENT,
  EMPLOYEE_ID  INT(11)  NOT NULL,
  CUSTOMER_ID  INT(11)  NOT NULL,
  JOB_ID       INT(11)  NOT NULL,
  APPLIED_DATE DATETIME NOT NULL,
  RESUME       LONGBLOB NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SAVED_JOB (
  ID          INT(11)  NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID INT(11)  NOT NULL,
  JOB_ID      INT(11)  NOT NULL,
  SAVED_DATE  DATETIME NOT NULL,
  PRIMARY KEY (ID)
);